# ---------- build ----------
FROM node:22-alpine AS builder
WORKDIR /app

COPY package.json package-lock.json ./
# npm install alinea el lock con package.json si el repo aún tiene un lock antiguo (ideal: commit de lock actualizado desde Node 22).
RUN npm install

COPY . .

# Vite inlines VITE_* at build time (must match production Cognito / API URLs)
ARG VITE_COGNITO_REGION
ARG VITE_COGNITO_USER_POOL_ID
ARG VITE_COGNITO_USER_POOL_CLIENT_ID
ARG VITE_COGNITO_DOMAIN
ARG VITE_COGNITO_REDIRECT_SIGN_IN
ARG VITE_COGNITO_REDIRECT_SIGN_OUT
ARG VITE_COGNITO_OAUTH_SCOPES
ARG VITE_CHAT_WS_URL
ARG VITE_AUTH_DEBUG=false

ENV VITE_COGNITO_REGION=$VITE_COGNITO_REGION
ENV VITE_COGNITO_USER_POOL_ID=$VITE_COGNITO_USER_POOL_ID
ENV VITE_COGNITO_USER_POOL_CLIENT_ID=$VITE_COGNITO_USER_POOL_CLIENT_ID
ENV VITE_COGNITO_DOMAIN=$VITE_COGNITO_DOMAIN
ENV VITE_COGNITO_REDIRECT_SIGN_IN=$VITE_COGNITO_REDIRECT_SIGN_IN
ENV VITE_COGNITO_REDIRECT_SIGN_OUT=$VITE_COGNITO_REDIRECT_SIGN_OUT
ENV VITE_COGNITO_OAUTH_SCOPES=$VITE_COGNITO_OAUTH_SCOPES
ENV VITE_CHAT_WS_URL=$VITE_CHAT_WS_URL
ENV VITE_AUTH_DEBUG=$VITE_AUTH_DEBUG

RUN npm run build

# ---------- runtime ----------
FROM nginx:1.27-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
